forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib'
mod 'puppetlabs/inifile'
mod 'puppetlabs/vcsrepo'

mod 'puppetlabs/apt'
mod 'puppetlabs/concat'
mod 'puppetlabs/apache'

mod 'mayflower/php', '4.0.0-beta1'
